---
- name: Deploy Student Management Application
  hosts: local
  connection: local
  become: false

  tasks:

    - name: Stop existing container
      community.docker.docker_container:
        name: student-management
        state: absent

    - name: Build Docker image
      community.docker.docker_image:
        name: student-management
        tag: latest
        source: build
        build:
          path: /mnt/d/student-management-devops

    - name: Start Student Management container
      community.docker.docker_container:
        name: student-management
        image: student-management:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "8082:8080"
